### ISSUE TITLE
v2.8.0 changelog?

### ISSUE THREAD

**Issue by ShockwaveNN** [rails/execjs#101]
I've recieved update via `dependabot`, but I cannot find any changelog or GitHub Release for this version

**Comment by ShockwaveNN** [comment]
Yeah, I understand that there is no changelog, but release 2.7.0 is formated as `GitHub Release`, but 2.8.0 is simple git tag
Maybe add some release notes to 2.8.0 also?
![image](https://user-images.githubusercontent.com/668524/117926483-85704a00-b301-11eb-8b96-5df23bb4fb54.png)

**Comment by byroot** [comment]
Here you go https://github.com/rails/execjs/releases/tag/v2.8.0

**Comment by ShockwaveNN** [comment]
@byroot Thanks, thas resolved my question )
