### ISSUE TITLE
An example in the README doesn't work

### ISSUE THREAD

**Issue by ttanimichi** [rails/execjs#109]
> `source = open("http://coffeescript.org/extras/coffee-script.js").read`

This line doesn't work due to a linkrot.

```sh
$ curl -is http://coffeescript.org/extras/coffee-script.js | head -n 1
HTTP/1.1 404 Not Found
```

**Comment by SheetJSDev** [comment]
The URL that works today (2023 February 14) is `http://coffeescript.org/browser-compiler-legacy/coffeescript.js`.
