### ISSUE TITLE
Setup bun.sh runtime

### ISSUE THREAD

**Issue by stevenbarragan** [rails/execjs#116]
It'd be nice to be able to use Bun. It promises super speed.

https://bun.sh/

**Comment by stevenbarragan** [comment]
Nvm, it's basically JavaScriptCore and execjs already has support for it

**Comment by yagarea** [comment]
@stevenbarragan How did you managed to use JavaScriptCore instead of node ?

**Comment by stevenbarragan** [comment]
If you don't have node available the next runtime it tries to use is [JavaScriptCore](https://github.com/rails/execjs/blob/master/lib/execjs/runtimes.rb#L92). I'm not sure if there is a way to specifically use JavaScriptCore regardless of the available runtimes in your environment.
