### ISSUE TITLE
bun.sh as runtime

### ISSUE THREAD

**Issue by yagarea** [rails/execjs#119]
Hello, is there way to use bun.sh as runtime ?

Thanks for support

**Comment by casperisfine** [comment]
See https://github.com/rails/execjs/issues/116

You can probably define an `ExternalRuntime` that call `bun run` https://github.com/rails/execjs/blob/master/lib/execjs/runtimes.rb#L21-L26

**Comment by yagarea** [comment]
Thanks for suggestion. I tried this:
```ruby
require 'execjs'
require 'execjs/runtimes'

PATH_TO_JS = File.join(__dir__, "/katex.min.js")
BUN = ExternalRuntime.new(
      name:        "Bun",
      command:     ["bun run"],
      #runner_path: ExecJS.root + "/support/node_runner.js",
      encoding:    'UTF-8'
)
KATEX = BUN.compile(open(PATH_TO_JS).read)
```
But I get 

```
project.rb:10:in `<top (required)>': uninitialized constant ExternalRuntime (NameError)
```
Am I accessing the ExternalRuntime class right ?

**Comment by casperisfine** [comment]
`ExecJS::ExternalRuntime.new`

**Comment by yagarea** [comment]
Thank you! You did great job.

Is there a way to force my program to select bun as runtime even I have nodejs and bun installed at the same time ?
