### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by walski** [rails/execjs#132]
Hey folks, thank you so much for maintaining this gem. Is there a way forward with which we could get a changelog for releases again? It has become a bit tedious to follow your releases by going through every single commit and trying to figure out if there are breaking changes or other things in a release that we'd need to be aware of before updating.

Thank you!!!

**Comment by rafaelfranca** [comment]
Changelogs are here https://github.com/rails/execjs/releases

**Comment by walski** [comment]
❤️
