### ISSUE TITLE
Freeze/hang when using ExecJS::RubyRacerRuntime concurrently.

### ISSUE THREAD

**Issue by kevincox** [rails/execjs#15]
Originally reported by @dtinth at sstephenson/execjs#162

> I'm developing a site using Middleman, apparently it is somehow threaded. Whenever multiple JavaScript is run in the same time using different threads, Ruby process freezes, cannot be interrupted, and must be kill -9ed.

Please see the original issue for more details and a test case.

## Related Issues
- middleman/middleman#1367

**Comment by pencilcheck** [comment]
:+1: Seems to affect Sprocket YUI compressor as well

**Comment by ryanstout** [comment]
I'm working on https://github.com/voltrb/volt and whenever I ```require 'therubyracer'```, then sprockets stops rendering if I load a page.  If I load the js/css files first (to cache them), and run them individually, it works.  So it would seem this is a race condition.  Same thing as above where I have to kill -9.  Hit me up if you need help duplicating.

Thanks

**Comment by SamSaffron** [comment]
therubyracer at the moment has a bunch of internal issues that can cause it to hang under multithreading, try running the mini_racer backend instead.

**Comment by rafaelfranca** [comment]
Agree. It is therubyracer issue
