### ISSUE TITLE
Error with Duktape backend

### ISSUE THREAD

**Issue by cygwinports** [rails/execjs#21]
Running the CoffeeScript example from README.md with Ruby 2.2.2, ExecJS 2.5.2, and duktape.rb 1.2.1.0:
```
irb(main):006:0> context.call("CoffeeScript.compile", "square = (x) -> x * x", bare: true)
TypeError: wrong argument type Symbol (expected String)
        from /usr/share/gems/gems/execjs-2.5.2/lib/execjs/duktape_runtime.rb:29:in `call_prop'
        from /usr/share/gems/gems/execjs-2.5.2/lib/execjs/duktape_runtime.rb:29:in `call'
        from (irb):6
        from /usr/bin/irb:11:in `<main>'
```
The example works fine with the JavaScriptCore backend (with jsc-3 from webkitgtk3).

**Comment by SamSaffron** [comment]
I find duktape to be a very incomplete js engine, I can not even minify our source with it. I do not think this is an execjs issue.

**Comment by rafaelfranca** [comment]
Agree. It is a Ducktape issue.
