### ISSUE TITLE
Change order of runtimes?

### ISSUE THREAD

**Issue by lunks** [rails/execjs#22]
Could we consider moving node.js up over JavaScriptCore?

I have node installed and AFAICT if you have node and a operating-system level javascript implementation, you'd rather use the one that you installed as opposed to the OS one.

**Comment by rafaelfranca** [comment]
There is any advantage?

**Comment by lunks** [comment]
I was having an issue when precompiling my javascript where jsc was segfaulting. Running with `EXECJS_RUNTIME=Node` worked, but that is not a very strong argument.

Looking at the list order (considering ruby gems selected by the developer would be chosen first) it makes sense to me to have node.js before JavaScriptCore because I can control/update it as I would with the higher priority runtimes.

If it is considered best to use OS implementations, then we could argue `JScript` should be higher in the list.

**Comment by lunks** [comment]
I've created a PR with the proposed change. Also, note that in the [README](https://github.com/rails/execjs#execjs) the order is the same as what I'm proposing.
