### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by Andre-Tischer** [rails/execjs#26]
I am using a js parser generator PEG. The newest version (0.9.0) of this lib crashes therubyracer in a segmentation fault. I have provided a zip file with test cases. 
I can make EXECJS work by executing some javascript code first and then call the PEG lib. 

Note that if i compile a factorize function and use it to generate the first two it makes the environment work when i subsequently call peg_0.9.0.min.js. If i only factorize the first number the PEG lib crashes. I have tried to provide a full range of testcases.

1) Unpack 
2) >ruby bug_report.rb
3) Open bug_report.rb and change the variable RUN_TEST_NUMBER to reflect what test you want to run.
https://dl.dropboxusercontent.com/u/12732287/execjs_bug.tar.gz

Regards,
   André
   ELUENCE

**Comment by SamSaffron** [comment]
This is very unlikely to be execjs related, can you try a different runtime (what runtime are you using?)

**Comment by rafaelfranca** [comment]
Closing for now but please let us know if you have more information.
