### ISSUE TITLE
Running multiple scripts in a single process

### ISSUE THREAD

**Issue by eapache** [rails/execjs#27]
@rafaelfranca I'm using execjs in a project where I'd like to run the same script many times against a set of inputs (specifically I want to run https://github.com/babel/ruby-babel-transpiler against a whole slew of javascript files).

This is currently extremely slow because it spins up a new sub-process for each file I'm processing. I've been poking around trying to figure out a way to have it only spin up the subprocess once and re-use it, which sounds like it ought to be trivial but I haven't been able to make it work.

Is this impossible? Possible-but-not-yet-implemented? Is there some other trick I'm missing?

I'd be happy to implement this feature with a little guidance if that isn't crazy.

**Comment by eapache** [comment]
Just found out that by also requiring `therubyracer` in my gem causes execjs to use some sort of compiled-in V8 engine and doesn't have to spin up a separate process at all. So much faster.

This leads to a couple of questions:
- Why doesn't `execjs` just depend on `therubyracer` and be done with it?
- Assuming there's a good answer to the above question, why isn't it documented in the README that "you probably want to also require `therubyracer` for decent performance"?

**Comment by rafaelfranca** [comment]
execjs supports many runtimes not just `therubyracer` so this is why it doesn't depends on it. README talks about all the available runtimes and that `execjs` choose the best one if installed. Do you think we need to improve it?

**Comment by eapache** [comment]
It would be nice if the list of runtimes were split into "these ones are fast" (racer and rhino presumably) vs "these ones are slow".

Also, why bother supporting many runtimes if `therubyracer` is always the best choice? (In other words: when might you actually want to use a different runtime?)

**Comment by rafaelfranca** [comment]
I don't think `therubyracer` is always the best choice. I'd bet that `node.js` is the best choice if you are not going to spin a lot of executions. Also `ducktime` runtime may be faster than `therubyracer` but I never tried it. There are also runtimes that don't work in some environments (which is the case of `therubyracer` and `therubyrhino`)

We cal split the list but that is the best runtime depends on the usage so it would be really hard to have a list that works for all the usages.

**Comment by eapache** [comment]
Alright, some kind of advice on choosing a runtime would be good documentation then.
