### ISSUE TITLE
README.md needs a LOT of work

### ISSUE THREAD

**Issue by Tectract** [rails/execjs#30]
I inheritted a code project that used Execjs. I'd like to learn more but there is so little info in the readme here, I'm having to just reverse-engineer it and learn by trial and error. How do I load a js file within a ruby file and access some class objects / methods from in there? How do I choose which interpreter it will use? Are there execjs "objects" and what are the subfunctions I would use to access them? Is there an API? I have no idea what I'm doing and the readme contains basically nothing that I see in my project code, so I'm totally lost with the execjs functionality.

**Comment by jeremy** [comment]
These are great questions. Here's the place to do the work! Sounds like you aren't so lost anymore :grin: As you come across questions and suss out the answer, could you open pull requests against the README to share with others?

**Comment by Tectract** [comment]
> Sounds like you aren't so lost anymore

What? No, I am still completely lost. I am just looking at using therubyracer now instead because it at least has some mention of how to load a js file within the readme. I'm even more confused that you agreed that the README.md file needs work, but however, closed this ticket.

**Comment by Tectract** [comment]
Really what I'd like to do is run a piece of node.js script from within a ruby module and either get some access to call the subfunctions on a nodejs object, or just have it return some json. Can you give me some help here, please?

**Comment by jeremy** [comment]
An open-ended "needs work" issue is a cry for help, not a specific issue to address. I hear that. You're going to need to do some spelunking to get up to speed. You're asking good questions, shining the light in the right directions (or, stubbing your toes in the right places!)

To get a more thorough introduction, start with real usage of the library. Check out [the test suite](https://github.com/rails/execjs/blob/master/test/test_execjs.rb#L46-L49), then explore other ExecJS users, like the [Ruby CoffeeScript compiler](https://github.com/josh/ruby-coffee-script/blob/master/lib/coffee_script.rb), the [Ruby Less compiler](https://github.com/maccman/less-rb/blob/master/lib/less/parser.rb), [Ruby JSLint](https://github.com/mintdigital/execjslint/blob/master/lib/jslint.rb), and [a full JavaScript renderer for Rails](https://github.com/revelrylabs/execjs-rails), among [others](https://github.com/search?q=execjs&type=Repositories).

**Comment by Tectract** [comment]
How does that help me accomplish the task of running nodejs code within a ruby module? I'm not trying to write coffeescript or render a view, I'm trying to run nodejs code, from within a ruby module. Apparently execjs can do that, somehow, but the readme doesn't explain how. Do you know?

**Comment by Tectract** [comment]
source = File.open("mynodejs_script.js", "r")
    context = ExecJS.compile(source)

...lib/execjs/encoding.rb:22:in `encode': undefined method `encode' for #<File:mynodejs_script.js> (NoMethodError)

uh, ok. well, it doesn't load the nodejs script. script runs just fine with "node mynodejs_script.js" though. Am I doing something wrong here?

**Comment by Tectract** [comment]
source = File.open("mynodejs_script.js", "r").read
    context = ExecJS.compile(source)

fails on:

(execjs):1:16: ReferenceError: require is not defined (ExecJS::ProgramError)

So I guess execjs can run nodejs code, but not js scripts which "require" nodejs code? Seems odd, but ok, maybe this isn't the tool for me.
