### ISSUE TITLE
ExecJS::ProgramError

### ISSUE THREAD

**Issue by jykoomson** [rails/execjs#39]
I have installed gem install execjcs
But still encountering this error

Started GET "/" for ::1 at 2016-05-16 00:31:18 +0100
  ActiveRecord::SchemaMigration Load (1.0ms)  SELECT "schema_migrations".* FROM
"schema_migrations"
Processing by MessagesController#index as HTML
  Message Load (0.0ms)  SELECT "messages".* FROM "messages"  ORDER BY created_at
 DESC
  Rendered messages/index.html.erb within layouts/application (23.0ms)
Completed 500 Internal Server Error in 15833ms (ActiveRecord: 1.0ms)

ActionView::Template::Error (TypeError: Object doesn't support this property or
method):
    2: <html>
    3: <head>
    4:   <title>MessageBoard</title>
    5:   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolink
s-track' => true %>
    6:   <%= javascript_include_tag 'application', 'data-turbolinks-track' => tr
ue %>
    7:   <%= csrf_meta_tags %>
    8: </head>
  app/views/layouts/application.html.erb:5:in `_app_views_layouts_application_ht
ml_erb__118342136_50222232'

**Comment by guilleiguaran** [comment]
What OS/engine are you using?

**Comment by jykoomson** [comment]
windows 7

On Mon, May 16, 2016 at 1:00 AM, Guillermo Iguaran <notifications@github.com

**Comment by jykoomson** [comment]
windows7/32bits

On Mon, May 16, 2016 at 1:00 AM, Guillermo Iguaran <notifications@github.com

**Comment by guilleiguaran** [comment]
I have experienced this problem in Windows 7 multiple times and the best solution so far was installing Node.js so ExecJS is able to pick Node.js as engine instead of JScript.

**Comment by jykoomson** [comment]
I've solved the problem.
installed gem 'coffee-script-source', '~> 1.8.0'
then bundle install
re-start server
done.

On Mon, May 16, 2016 at 3:08 AM, Guillermo Iguaran <notifications@github.com

**Comment by dub357** [comment]
Monkey patch for this issue here:
https://github.com/rails/rails/issues/31983#issuecomment-429029707
