### ISSUE TITLE
Why is mini_racer optional for contributing flow?

### ISSUE THREAD

**Issue by junaruga** [rails/execjs#47]
When I tried to set up my development environment,
following
https://github.com/rails/execjs/blob/master/CONTRIBUTING.md
Bundle install and test

I got the error. can not find mini_racer.
Why is mini_racer not installed on default setting?
https://github.com/rails/execjs/blob/master/Gemfile#L8

Maybe contributor wants to succeed all the test "bundle exec rake" without installing mini_racer manually.

```
$ git clone https://github.com/contributor/execjs.git

$ cd execjs

$ bundle install --path vendor/bundle

$ bundle list
Gems included by the bundle:
  * bundler (1.12.5)
  * duktape (1.3.0.6)
  * execjs (2.7.0)
  * libv8 (3.16.14.15)
  * minitest (5.9.0)
  * rake (11.2.2)
  * ref (2.0.0)
  * therubyracer (0.12.2)

$ bundle exec rake
...
Could not find gem 'mini_racer (= 0.1.0.beta.3)' in any of the gem sources listed in your Gemfile or available on this machine.
Run `bundle install` to install missing gems.
...
PASSED:  test:duktape, test:node, test:rubyracer
SKIPPED: test:javascriptcore, test:jscript, test:rubyrhino, test:v8
FAILED:  test:miniracer
...
```

**Comment by matthewd** [comment]
Because it's mutually exclusive with `therubyracer`.

Looks like we need to add a `EXECJS_RUNTIME=MiniRacer bundle install` command to CONTRIBUTING. Want to send a patch?

**Comment by junaruga** [comment]
Okay I got it.

> Looks like we need to add a EXECJS_RUNTIME=MiniRacer bundle install command to CONTRIBUTING. Want to send a patch?

It looks good idea.
Yes, I want to send you my patch as a pull-request. Just moment.
