### ISSUE TITLE
Runtime Benchmarks

### ISSUE THREAD

**Issue by moserke** [rails/execjs#53]
Have any benchmarks been run against the various runtimes?  Would be nice to have an understanding of the performance tradeoffs of each of the runtimes.

**Comment by rafaelfranca** [comment]
Not that we are aware of. The best benchmarks are those did in the same environment we want to use 😄 . Take this opportunity to share your results with the community

**Comment by ignisf** [comment]
Yes, there have been a few benchmarks comparing node, therubyracer, and mini_racer. [mini_racer](https://github.com/discourse/mini_racer#performance) has a makeshift benchmark suite you can try out if you'd like to, but AFAIK performance-wise mini_racer is in the lead just ahead of node.

**Comment by ignisf** [comment]
Here are some pretty graphs: https://github.com/cowboyd/libv8/issues/150#issuecomment-219343434
