### ISSUE TITLE
ExecJS::ProgramError: TypeError: Cannot assign to read only property '__esModule' of #<Object>

### ISSUE THREAD

**Issue by jmaggesi** [rails/execjs#63]
Hi to all,
i've tried to precompile the assets of one of my project in a server already running.

If i try to precompile the assets in my local machine it works as expected but on the server during the precompilation of the assets the task fail with the output attached in the note of the issue.

Do you have any suggestions to solve the issue or a way to find how to solve the problem ?

Thanks

[Log-Example.txt](https://github.com/rails/execjs/files/1099875/Log-Example.txt)

**Comment by kevinchugh** [comment]
Ever find a solution for this @jmaggesi ? I have the exact same problem. Works fine locally, spits out exact same error on server.

**Comment by rafael-acerqueira** [comment]
I have the same problem. Do you know how to fix it ?

**Comment by kevinchugh** [comment]
Upgrading node.js to the latest version solved this for me, @rafael-acerqueira . Hope this helps.

**Comment by rafaelfranca** [comment]
This doesn't seems to be an issue on execjs, but an issue in the runtime. Closing.
