### ISSUE TITLE
Custom configuration of runtime

### ISSUE THREAD

**Issue by willcosgrove** [rails/execjs#71]
Would the maintainers of this gem be receptive to a PR to add the ability to arbitrarily configure the runtimes?

The specific use case I have in mind is this: With the MiniRacer (and possibly others, I'm only familiar with MiniRacer) gem, you can attach a ruby proc to the property of an object, making it easy to call back to ruby from your JS.  But because `ExecJS::MiniRacerRuntime` creates its own `MiniRacer::Context` and does not allow you to pass one in, there is no easy way to configure it.

My initial thought on how to do this would be to allow passing an optional block to the `ExecJS::Runtime#compile` that could either yield the instantiated context, or it could pass the block to the Context's initializer which could do whatever it wants with it, like yielding the actual 3rd party context.

I would be happy to work on a PR to add this functionality if anyone else is interested in it.

**Comment by matthewd** [comment]
I don't see how that would be useful in this library... if you're configuring runtime-specific behaviour, why not just talk to the runtime directly?

The benefit of ExecJS is that it provides an extremely coarse abstract API that can be implemented by many different runtimes: if you want functionality that is only possible in limited conditions, it doesn't seem to have anything to offer. 🤷🏻‍♂️

**Comment by willcosgrove** [comment]
That makes sense.  In my case, I'm not the direct user of ExecJS, I have a dependency that is using it.  And I'm without a way to configure ExecJS to use my preconfigured runtime instance.
