### ISSUE TITLE
Rails with Ruby 2.3.6, Ruby 2.4.3, Ruby 2.5.0 fail to run with Apache + Passenger

### ISSUE THREAD

**Issue by Sega100500** [rails/execjs#72]
Rails with **Ruby 2.3.6**, **Ruby 2.4.3**, **Ruby 2.5.0** fail to run with Apache + Passenger
Apache/2.4.10 (Debian)
Passenger 5.1.12

ALL applications out:
**Incomplete response received from application**

Before versions of Ruby ALL works fine!

In log-file:
```
App 31519 stderr: /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/therubyracer-0.12.3/lib/v8/context.rb:99: [BUG] Segmentation fau
lt at 0x0000000000000000
App 31519 stderr: ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux]
App 31519 stderr:
App 31519 stderr: -- Control frame information -----------------------------------------------
App 31519 stderr: c:0161 p:---- s:1007 e:001006 CFUNC  :Run
App 31519 stderr: c:0160 p:0006 s:1003 e:001002 BLOCK  /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/therubyracer-0.12.3/lib/v8/
context.rb:99
```

_But!!! **therubyracer** is a PART of Ruby on Rails._
However, it seems that this gem (**therubyracer**) has long since died and is no longer supported (Latest commit 466a1f0 on 5 Jan).

Without ```gem 'therubyracer', platforms: :ruby``` in Gemfile no one application not working (even in development mode - without Apache+Passenger - ```rails -s```)!

PLEASE HELP!!!

[passenger.level7.log.therubyracer.bug.log](https://github.com/rails/execjs/files/1588568/passenger.level7.log.therubyracer.bug.log)

**Comment by Sega100500** [comment]
ExecJS bug in log-file:

```
App 31519 stderr: c:0152 p:---- s:0972 e:000971 CFUNC  :Locker
App 31519 stderr: c:0151 p:0037 s:0968 E:000f18 METHOD /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/therubyracer-0.12.3/lib/v8/
context.rb:244
App 31519 stderr: c:0150 p:0016 s:0963 e:000962 METHOD /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/therubyracer-0.12.3/lib/v8/
context.rb:204
App 31519 stderr: c:0149 p:0047 s:0958 E:000eb8 METHOD /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/therubyracer-0.12.3/lib/v8/
context.rb:94
App 31519 stderr: c:0148 p:0027 s:0951 e:000950 BLOCK  /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/rub
y_racer_runtime.rb:13
App 31519 stderr: c:0147 p:0003 s:0947 e:000946 BLOCK  /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/rub
y_racer_runtime.rb:75 [FINISH]
App 31519 stderr:
App 31519 stderr: c:0146 p:---- s:0943 e:000942 CFUNC  :Locker
App 31519 stderr: c:0145 p:0019 s:0939 E:000af0 METHOD /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/rub
y_racer_runtime.rb:73
App 31519 stderr: c:0144 p:0021 s:0933 E:000a88 METHOD /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/rub
y_racer_runtime.rb:9 [FINISH]
App 31519 stderr: c:0143 p:---- s:0926 e:000925 CFUNC  :new
App 31519 stderr: c:0142 p:0046 s:0919 e:000918 METHOD /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/run
time.rb:57
App 31519 stderr: c:0141 p:0015 s:0913 e:000912 METHOD /home/ruby/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/execjs-2.7.0/lib/execjs/mod
ule.rb:27
```

**Comment by kamipo** [comment]
This seems therubyracer issue. You can try to use other runtimes which are supported by ExecJS.

**Comment by Sega100500** [comment]
@kamipo 
> You can try to use other runtimes which are supported by ExecJS.
What are the variants of other gems indtead ```therubyracer```?

Ok. Because ```therubyracer``` is a PART of Ruby on Rails, and ```therubyracer``` is died (Latest commit 466a1f0 on 5 Jan) then **Ruby on Rails also will die with newest version of Ruby 2.3.6, 2.4.3, 2.5.0**.

Or any one may correct the gem ```therubyracer```?

**Comment by guilleiguaran** [comment]
You can use `mini_racer` instead of `therubyracer` or install Node.js in the system.

**Comment by Sega100500** [comment]
@guilleiguaran 
already install to use NodeJS - works!
mini_racer - this not installed too (as therubyracer working with errors)
