### ISSUE TITLE
Clarify what are valid values for "identifier" in #call

### ISSUE THREAD

**Issue by judofyr** [rails/execjs#76]
`Context#call(identifier, *args)` is only tested against these identifiers in the test case:

- `"id"`
- `"a.b.id"`
- `"CoffeeScript.eval"`

However, in the wild ([example for Autoprefixer Rails](https://github.com/ai/autoprefixer-rails/blob/7b44387ebe8799f5be864a051b791268ad80d81e/lib/autoprefixer-rails/processor.rb#L24)) people are sending full JavaScript code as the "identifier". This works on some backend (Node.js), but fails on others (Duktape). What is the intended behaviour here? Should Duktape support full JavaScript in `identifier`, or should Autoprefixer Rails be fixed to first define it as a function?

**Comment by rafaelfranca** [comment]
What is the behavior of other runtimes like mini_racer and therubyracer?

**Comment by judofyr** [comment]
- RubyRacer: Supports any JavaScript as identifier
- MiniRacer: Also supports any JavaScript as identifier, but it's implemented as eval + `JSON.generate(args)` (see [the TODO in the source](https://github.com/rails/execjs/blob/5f78865d36976f85b42e8529dec272285d8f3b85/lib/execjs/mini_racer_runtime.rb#L33)) instead being directly serialized into the runtime.

**Comment by rafaelfranca** [comment]
In that case I believe Duktabe should also support any JavaScript as identifier.

**Comment by judofyr** [comment]
I'll try to create a PR with updated tests and documentation.
