### ISSUE TITLE
What secure reason we have with sandbox scripts?

### ISSUE THREAD

**Issue by mpz** [rails/execjs#78]
From readme.md

> Can ExecJS be used to sandbox scripts?
> 
> No, ExecJS shouldn't be used for any security related sandboxing. Since runtimes are automatically detected, each runtime has different sandboxing properties. You shouldn't use ExecJS.eval on any inputs you wouldn't feel comfortable Ruby eval()ing.

My runtime is Node.js (V8)
Can i use it for sandboxing? There are no `require` and `import`.

**Comment by matthewd** [comment]
I'm not sure what further information we can offer:

> Since runtimes are automatically detected, each runtime has different sandboxing properties.

If you believe a particular runtime can be trusted to run code in a sandboxed environment (and I have no opinion on whether that's true), then that's a use case for calling that runtime directly. ExecJS is an abstraction layer over many runtimes, so the guarantees it can offer are much weaker.
