### ISSUE TITLE
启动rails server 报错，我是使用root用户启动的服务。

### ISSUE THREAD

**Issue by AlZero-t** [rails/execjs#82]
[root@test-itsm bin]# rails server 
/root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/execjs-2.7.0/lib/execjs/runtimes.rb:58:in `autodetect': Could not find a JavaScript runtime. See https://github.com/rails/execjs for a list of available runtimes. (ExecJS::RuntimeUnavailable)
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/execjs-2.7.0/lib/execjs.rb:5:in `<module:ExecJS>'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/execjs-2.7.0/lib/execjs.rb:4:in `<top (required)>'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/uglifier-4.1.19/lib/uglifier.rb:5:in `<top (required)>'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.17.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.17.1/lib/bundler/runtime.rb:76:in `each'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.17.1/lib/bundler/runtime.rb:76:in `block in require'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.17.1/lib/bundler/runtime.rb:65:in `each'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.17.1/lib/bundler/runtime.rb:65:in `require'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bundler-1.17.1/lib/bundler.rb:114:in `require'
	from /cpic/cpicapp/rbenv/plugins/ruby-build/share/ruby-build/blog/config/application.rb:7:in `<top (required)>'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.2.1/lib/rails/commands/server/server_command.rb:145:in `block in perform'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.2.1/lib/rails/commands/server/server_command.rb:142:in `tap'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.2.1/lib/rails/commands/server/server_command.rb:142:in `perform'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.2.1/lib/rails/command/base.rb:65:in `perform'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.2.1/lib/rails/command.rb:46:in `invoke'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-5.2.1/lib/rails/commands.rb:18:in `<top (required)>'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:65:in `register'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/bootsnap-1.3.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `block in require'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:253:in `load_dependency'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-5.2.1/lib/active_support/dependencies.rb:287:in `require'
	from /cpic/cpicapp/rbenv/plugins/ruby-build/share/ruby-build/blog/bin/rails:9:in `<top (required)>'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
	from /root/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
	from /root/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /root/.rbenv/versions/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /cpic/cpicapp/rbenv/plugins/ruby-build/share/ruby-build/blog/bin/spring:15:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'

**Comment by robin850** [comment]
As the error states, you don't have any JavaScript runtime. You need to uncomment the following in your Gemfile:

~~~ruby
# gem 'mini_racer', platforms: :ruby
~~~

And run `bundle install` or as another possible solution, install Node.js. Also please in the future, use English to fill your ticket ; this will be easier for people to help you.
