### ISSUE TITLE
How to disable execjs in runtime?

### ISSUE THREAD

**Issue by hopewise** [rails/execjs#93]
Hello

I am having an issue, as I do repcompile assets before I copy the app folder into the container for dockerized deployment.
What I notice is that for the first cur of the website, nodeJS would start a process for a long time eating up the CPU, then the second curl request would go fast.

I don't need to use javascript at run time, I tried the following in the Dockerfile:

```
ENV RAILS_SERVE_STATIC_FILES false
ENV EXECJS_RUNTIME=Disabled
ENV WEBPACKER_PRECOMPILE=false
```

Also as for production.rb:

```
config.serve_static_assets  = false
  config.serve_static_files  = false
  config.assets.compile = false
  config.assets.digest = true
  config.assets.enabled = true
  config.assets.initialize_on_precompile = true
```
For curl, the second request worked:

```
HTTP/2 200 
date: Wed, 16 Sep 2020 10:04:25 GMT
content-type: text/html; charset=utf-8
status: 200 OK
cache-control: max-age=0, private, must-revalidate
vary: Accept-Encoding
referrer-policy: strict-origin-when-cross-origin
x-permitted-cross-domain-policies: none
x-xss-protection: 1; mode=block
x-request-id: 36365117-7db6-4f82-a79f-d575fd6ce0bd
x-download-options: noopen
etag: W/"f4bb89ba5383f9e1d90e43aef5bc8a67"
x-frame-options: SAMEORIGIN
x-runtime: 0.019307
x-content-type-options: nosniff
set-cookie: XSRF-TOKEN=tNkG8EGyxBvADeySy5WgOTljAx4pbhZf0uH1pRPIMDczf5gPl5NBQNsHL6kti6aEs4MIRqk3fRARqqkVWHAQ5w%3D%3D; path=/
set-cookie: _dca_session=bVJMUmVIcjZzK0FmM1pFNXFqbXhldnNhVXhCYkREWnFKRkFWQno5TFNqMHRiU2VPcHRMa2VFcTZPbHJ0T1dQZUJGM2VMSnk4bU83bzJRT2VaZDZtYktMTTRPRW40Q2c1eGUvWklEZ3k2M1gwZk9OK3dkSXBET3g0bWlqcmdYQ050T1ZWNWVGNVVTYmliUVJYbVdzS2x4ajI3S3dOVU94VSt3VllSVzduMCthL1UxYVNIaTN3L2EwVEdDVFk4L1lMLS1nejU4SzJab0cvcFE1OTRPYlIrMmZnPT0%3D--3d67f57099f5c064f29adbda9a1af1ddf203602d; path=/; expires=Wed, 16 Sep 2020 12:04:25 GMT; HttpOnly
x-powered-by: Phusion Passenger 6.0.6
server: nginx/1.14.0 + Phusion Passenger 6.0.6
```
I also tried to reach out the community here: https://stackoverflow.com/questions/63895516/why-nodejs-process-starts-when-requesting-rails-app

Please advice.

**Comment by reiz** [comment]
That's a very good question! I wonder why there are no answers here.

**Comment by casperisfine** [comment]
Because this isn't supposed to happen. When you set ` config.assets.compile = false` ExecJS isn't invoked as part of the request cycle.

So the author of the issue must have something wrong in their app, that nobody else experienced.

**Comment by reiz** [comment]
In my `production.rb` I have `config.assets.compile = false`. But on production I get anyway this error: 

```
! Unable to load application: ExecJS::RuntimeUnavailable: Node.js (V8) runtime is not available on this system
```

Any idea what could cause it?

**Comment by reiz** [comment]
I found it! I had an entry in my `boot.rb` like this: 

```Ruby
ENV["BUNDLE_GEMFILE"] ||= File.expand_path("../Gemfile", __dir__)

require "bundler/setup" # Set up gems listed in the Gemfile.
require "bootsnap/setup" # Speed up boot time by caching expensive operations.

ENV['EXECJS_RUNTIME'] = 'Node'
```

After completely removing the last line, it worked on production without any Node runtime.
