### ISSUE TITLE
External runtimes broken on Ruby 3.0

### ISSUE THREAD

**Issue by daniel-rikowski** [rails/execjs#97]
External runtimes no long work in Ruby 3.0 due to [the separation of positional and keyword arguments](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/). 

This is the same problem as #91 but now the deprecation warning of Ruby 2.7 turned into broken code in Ruby 3.0.

The existing pull request #95 fixes this bug.

**Comment by jeffque** [comment]
I am now facing this very issue

**Comment by byroot** [comment]
I merged #95. However ExecJS is in dire need of a cleanup before we can cut a new version.

**Comment by daniel-rikowski** [comment]
> I merged #95. 

Thank you!

> However ExecJS is in dire need of a cleanup before we can cut a new version.

Perhaps you can add the necessary tasks to #94. It looks like a few people (including me) are willing to help.

**Comment by byroot** [comment]
Yeah, I'm still figuring out what's need. The first thing is to get a working CI because we're still on Travis.

**Comment by jeffque** [comment]
@byroot I am really used with gitlab-ci.

I know that the main goal should be within github (thus github actions), but perharps it could be a bandaid for a while?

**Comment by byroot** [comment]
Thanks, but I don't think that's necessary.
